name: linear
channels:
  - pytorch
  - conda-forge
dependencies:
  - _libavif_api=1.3.0=h57928b3_0
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - amply=0.1.6=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - black=25.1.0=pyh866005b_0
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - click=8.2.1=pyh7428d3b_0
  - cmake=4.0.2=hff78f93_0
  - coin-or-cbc=2.10.12=h1c9cd67_2
  - coin-or-cgl=0.60.9=h8aa12e5_4
  - coin-or-clp=1.17.10=ha4dcb5c_1
  - coin-or-osi=0.108.11=h7d32387_4
  - coin-or-utils=2.11.12=hf90b928_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313hf069bd2_3
  - cpython=3.13.9=py313hd8ed1ab_101
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.17=py313h927ade5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - eigen=3.4.0=h91493d7_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=8.0.0=gpl_he3062b8_906
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py313hd650c13_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.10=h8d14728_0
  - gdk-pixbuf=2.44.4=h1f5b9c4_0
  - glslang=16.0.0=h5b34520_0
  - gmp=6.3.0=hfeafd45_2
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=12.2.0=h5f2951f_0
  - hdf5=1.14.6=nompi_hd5d9e70_101
  - highspy=1.12.0=np2py313h776c0ec_0
  - icu=75.1=he0c23c2_0
  - imath=3.2.2=h1608b31_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.8=h8ad263b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py313h1a38498_2
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.3=h63175ca_0
  - libasprintf=0.22.5=h5728263_3
  - libavif16=1.3.0=he916da2_2
  - libblas=3.9.0=31_h641d27c_mkl
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=31_h5e41251_mkl
  - libclang13=21.1.5=default_ha2db4b5_0
  - libcurl=8.14.1=h88aaa65_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.1.0=h1383e82_2
  - libgettextpo=0.22.5=h5728263_3
  - libglib=2.86.1=hd9c3897_1
  - libgomp=15.1.0=h1383e82_2
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libjxl=0.11.1=hac9b6f3_5
  - liblapack=3.9.0=31_h1aa476e_mkl
  - liblapacke=3.9.0=31_h845c4fa_mkl
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.12.0=qt6_py313h3391bc2_607
  - libopenvino=2025.2.0=hbf28c98_1
  - libopenvino-auto-batch-plugin=2025.2.0=hdd9a157_1
  - libopenvino-auto-plugin=2025.2.0=hdd9a157_1
  - libopenvino-hetero-plugin=2025.2.0=hc39e7c6_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-ir-frontend=2025.2.0=hc39e7c6_1
  - libopenvino-onnx-frontend=2025.2.0=hee3bb10_1
  - libopenvino-paddle-frontend=2025.2.0=hee3bb10_1
  - libopenvino-pytorch-frontend=2025.2.0=hac47afa_1
  - libopenvino-tensorflow-frontend=2025.2.0=h293fe96_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hac47afa_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_1
  - librsvg=2.60.0=hd5e4115_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h550210a_0
  - libusb=1.0.29=h1839187_0
  - libuv=1.51.0=h2466b09_0
  - libvorbis=1.3.7=h0e60522_0
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - make=4.4.1=h0e40799_2
  - matplotlib=3.10.7=py313hfa70ccb_0
  - matplotlib-base=3.10.7=py313he1ded55_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2024.2.2=h66d3029_15
  - mkl-include=2024.2.2=h66d3029_15
  - mkl-static=2024.2.2=h66d3029_15
  - mpfr=4.2.1=hbc20e70_3
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.3.4=py313hce7ae62_0
  - opencl-headers=2024.10.24=he0c23c2_0
  - opencv=4.12.0=qt6_py313hea2c21c_607
  - openexr=3.4.2=hce16647_1
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.3=h24db6dd_1
  - openjph=0.25.2=hf13a347_0
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=h03d888a_0
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre2=10.46=h3402e2f_0
  - pillow=11.3.0=py313hf455b62_3
  - pip=25.2=pyh145f28c_0
  - pixman=0.46.2=had0cd8c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py313h5fd188c_0
  - pthread-stubs=0.4=h0e40799_1002
  - pugixml=1.15=h372dad0_0
  - pulp=2.8.0=py313h4a748c7_3
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py313h28b3a31_607
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-global=2.13.6=pyh6a1d191_3
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.3=py313h475ba69_1
  - pytest=8.4.1=pyhd8ed1ab_0
  - python=3.13.9=h09917c8_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.9=h4df99d1_101
  - python_abi=3.13=8_cp313
  - pywin32=311=py313h40c08fc_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_1
  - rav1e=0.7.1=ha073cba_3
  - sdl2=2.32.56=h5112557_0
  - sdl3=3.2.26=h5112557_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=haa9a63f_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - spirv-tools=2025.4=h49e36cd_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2021.13.0=hd094cb3_4
  - tk=8.6.13=h2c6b04d_2
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.5.2=py313h5ea7bf4_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=17.0.0=py313h5ea7bf4_0
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.44.35208=h818238b_26
  - vs2015_runtime=14.44.35208=h38c0c73_26
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - pysmps==1.5.6
      - scipy==1.16.3
prefix: C:\Users\rejil\miniforge3\envs\linear
